---

- hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/env python3'
  tasks:
    - git:
        repo: 'https://github.com/syl20bnr/spacemacs'
        dest: ~/.emacs.d

    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - spacemacs
