---
- hosts: all

  tasks:
    - apt_repository:
        repo: "ppa:jonathonf/vim"
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - package: name=vim-nox state=latest
      become: yes

    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - file: path=~/.vim/{{ item }} state=directory recurse=Yes
      with_items:
        - autoload

    # - file: src={{ curdir }}/files/vimrc dest=~/.config/nvim/init.vim state=link

    # - pip: name=neovim state=latest
    #   become: yes

    - get_url:
        force: yes
        dest: ~/.vim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    # - git:
    #     repo: 'https://github.com/VundleVim/Vundle.vim.git'
    #     dest: ~/.vim/bundle/Vundle.vim
        # version: v0.10.2

    - file: path=~/.vim/spell state=directory

    # - command: nvim -i NONE -c PlugUpdate -c quitall
    # FIXME: compile https://github.com/Shougo/vimproc.vim
